import Layout from '../components/Layout';

const PrivacyPolicy = () => {
  return (
    <Layout>
      <div className="bg-gray-50 py-24">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="bg-white rounded-lg shadow overflow-hidden">
            <div className="p-6 sm:p-8">
              <div className="prose prose-blue max-w-none">
                <h1 className="text-3xl font-bold text-gray-900 mb-2">Privacy Policy for TributoCR</h1>
                <p className="text-gray-500 mb-6">Last updated: August 15, 2025</p>

                <p className="text-gray-600 mb-6">
                  This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
                </p>

                <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">Interpretation and Definitions</h2>
                
                <h3 className="text-xl font-medium text-gray-900 mt-6 mb-3">Interpretation</h3>
                <p className="text-gray-600 mb-4">
                  The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                </p>

                <h3 className="text-xl font-medium text-gray-900 mt-6 mb-3">Definitions</h3>
                <div className="bg-gray-50 rounded-lg p-6 mb-6">
                  <ul className="space-y-4 text-gray-600">
                    {[
                      { term: 'Account', def: 'means a unique account created for You to access our Service or parts of our Service.' },
                      { term: 'Affiliate', def: 'means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.' },
                      { term: 'Application', def: 'refers to TributoCR, the software program provided by the Company.' },
                      { term: 'Company', def: '(referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to TributoCR.' },
                      { term: 'Country', def: 'refers to: Costa Rica' },
                      { term: 'Device', def: 'means any device that can access the Service such as a computer, a cellphone or a digital tablet.' },
                      { term: 'Personal Data', def: 'is any information that relates to an identified or identifiable individual.' },
                      { term: 'Service', def: 'refers to the Application.' },
                      { term: 'Service Provider', def: 'means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.' },
                      { term: 'Usage Data', def: 'refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).' },
                      { term: 'You', def: 'means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.' },
                    ].map(({ term, def }) => (
                      <li key={term}>
                        <span className="font-medium text-gray-900">{term}</span>: {def}
                      </li>
                    ))}
                  </ul>
                </div>

                <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">Collecting and Using Your Personal Data</h2>
                
                <h3 className="text-xl font-medium text-gray-900 mt-6 mb-3">Types of Data Collected</h3>
                
                <h4 className="text-lg font-medium text-gray-900 mt-4 mb-2">Personal Data</h4>
                <p className="text-gray-600 mb-4">
                  While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
                </p>
                <ul className="list-disc list-inside text-gray-600 mb-6">
                  <li>Email address</li>
                  <li>First name and last name</li>
                  <li>Usage Data</li>
                </ul>

                <h4 className="text-lg font-medium text-gray-900 mt-4 mb-2">Usage Data</h4>
                <p className="text-gray-600 mb-4">
                  Usage Data is collected automatically when using the Service.
                </p>

                <div className="bg-blue-50 border-l-4 border-blue-400 p-4 my-6">
                  <p className="text-blue-700">
                    When You access the Service by or through a mobile device, We may collect certain information automatically, including:
                  </p>
                  <ul className="list-disc list-inside text-blue-600 mt-2">
                    <li>Device type and unique identifiers</li>
                    <li>IP address</li>
                    <li>Operating system</li>
                    <li>Browser type and version</li>
                    <li>Usage statistics and diagnostic data</li>
                  </ul>
                </div>

                <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">Use of Your Personal Data</h2>
                <p className="text-gray-600 mb-4">
                  The Company may use Personal Data for the following purposes:
                </p>
                <ul className="list-disc list-inside text-gray-600 space-y-2 mb-6">
                  <li>To provide and maintain our Service</li>
                  <li>To manage Your Account</li>
                  <li>For the performance of a contract</li>
                  <li>To contact You</li>
                  <li>To manage Your requests</li>
                  <li>For business transfers</li>
                  <li>For data analysis and service improvement</li>
                </ul>

                <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">Security of Your Personal Data</h2>
                <div className="bg-yellow-50 border-l-4 border-yellow-400 p-4 my-6">
                  <p className="text-yellow-700">
                    The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
                  </p>
                </div>

                <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">Children's Privacy</h2>
                <p className="text-gray-600 mb-6">
                  Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13.
                </p>

                <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">Changes to this Privacy Policy</h2>
                <p className="text-gray-600 mb-6">
                  We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date.
                </p>

                <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">Contact Us</h2>
                <p className="text-gray-600 mb-6">
                  If you have any questions about this Privacy Policy, You can contact us:
                </p>
                <p className="text-gray-600">
                  By email: <a href="mailto:contact@savaldev.com" className="text-blue-600 hover:text-blue-500">contact@savaldev.com</a>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </Layout>
  );
};

export default PrivacyPolicy;
